spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/ApolloConfigDb
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
